version: '3.9'

services:
  redis:
    image: redis
    container_name: some-redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: always
    ports:
      - 6379:6379